## DUBBO接口版本号
amd:
  service:
    version: 1.0.0
##指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: DNacosDemo-provider
  protocol:
    name: dubbo
    port: 10880
  registry:
    id: nacos
    address: nacos://192.168.3.121:8848
  provider:
    loadbalance: roundrobin
    timeout: 1000




