server:
  port: 9901
spring:
  profiles:
    include: mybatis
    active: dev
  application:
    name: DNacosDemo
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB
  redis:
    host: 192.168.3.212
    port: 6379
    password: Amaidan@123456
    database: 1


# 暴露监控端点后会打印所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

## 控制接口版本号
amd:
  service:
    version: 1.0.0
##指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: DNacosDemo-provider
  protocol:
    name: dubbo
    port: 10880
  registry:
    address: zookeeper://192.168.3.227:2181
  provider:
    timeout: 1000


# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapping/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true


