server:
  port: 9901
spring:
  profiles:
    include: mybatis,dubbo
    active: dev
  application:
    name: DNacosDemo
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB


# 暴露监控端点后会打印所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'




